---
- name: Hello World test playbook
  hosts: all
  tasks:
    - name: Calling the role to check the environment
      ansible.builtin.include_role:
        name: rhsiqe.skupper.env_shakeout

    - name: Calling the role to generate the namespaces
      ansible.builtin.include_role:
        name: rhsiqe.skupper.generate_namespaces
      vars:
        namespace_prefix: zago

    - name: Deploying backend and frontend
      ansible.builtin.include_role:
        name: rhsiqe.skupper.deploy_workload
      vars:
        namespace_prefix: zago

    - name: Installing Skupper
      ansible.builtin.include_role:
        name: rhsiqe.skupper.install_skupper
      when:
        - "'west' in inventory_hostname"
        - not skip_skupper_install | default(false) | bool

    - name: Creating Skupper sites
      ansible.builtin.include_role:
        name: rhsiqe.skupper.skupper_site
      vars:
        namespace_prefix: zago

    - name: Deleting namespaces
      ansible.builtin.include_role:
        name: rhsiqe.skupper.teardown_namespaces
      vars:
        namespace_prefix: zago
