---
- name: Hello World test playbook
  hosts: all
  vars:
    namespace_prefix: zago

  tasks:
    - name: Calling the role to check the environment
      ansible.builtin.include_role:
        name: rhsiqe.skupper.env_shakeout

    - name: Calling the role to generate the namespaces
      ansible.builtin.include_role:
        name: rhsiqe.skupper.generate_namespaces

    - name: Deploying backend and frontend
      ansible.builtin.include_role:
        name: rhsiqe.skupper.deploy_workload

    - name: Installing Skupper
      ansible.builtin.include_role:
        name: rhsiqe.skupper.install_skupper
      when:
        - not skip_skupper_install | default(false) | bool

    - name: Creating Skupper sites
      ansible.builtin.include_role:
        name: rhsiqe.skupper.skupper_site

    - name: Deleting namespaces
      ansible.builtin.include_role:
        name: rhsiqe.skupper.teardown_namespaces
