- name: Debug cluster check for {{ item.key }}
  ansible.builtin.debug:
    msg: "Checking connection to the cluster: {{ item.key }}"

- name: Check cluster connection for {{ item.key }}
  kubernetes.core.k8s_info:
    kubeconfig: "{{ item.value }}"
    kind: "Node"
  register: cluster_check
  ignore_errors: true

- name: Connection failure - {{ item.key }}
  ansible.builtin.fail:
    msg: "Failed to connect to the cluster: {{ item.key }}"
  when: cluster_check.failed
