---
# roles/teardown_namespaces/tasks/main.yml
- name: Create namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    kind: Namespace
    name: "{{ namespace_prefix }}-{{ namespace_name }}"
  register: namespace

- name: Display namespace name
  ansible.builtin.debug:
    msg: "Namespace deleted: {{ namespace.result.metadata.labels['kubernetes.io/metadata.name'] }}"
