---
# roles/teardown_test/tasks/main.yml
- name: Deleting test namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    kind: Namespace
    name: "{{ namespace_prefix }}-{{ namespace_name }}"
  register: namespace

- name: Waiting for namespace deletion
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Namespace
    name: "{{ namespace_prefix }}-{{ namespace_name }}"
  register: namespace_info
  until: namespace_info.resources | length == 0
  retries: 20
  delay: 2
  failed_when: false

- name: Deleting test temporary directory
  ansible.builtin.file:
    path: "{{ teardown_test_temp_dir_path }}"
    state: absent

- name: Display deleted resources
  ansible.builtin.debug:
    msg: |
      Cleanup Summary:
      - Namespace: {{ namespace.result.metadata.name if namespace.result is defined else 'N/A' }}
      - Temporary Directory: {{ teardown_test_temp_dir_path }}
