---
# roles/teardown_test/tasks/main.yml
- name: Deletiing test namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    kind: Namespace
    name: "{{ namespace_prefix }}-{{ namespace_name }}"
  register: namespace

- name: Deleting test temporary directory
  ansible.builtin.file:
    path: "{{ teardown_test_temp_dir_path }}"
    state: absent

- name: Display deleted resources
  ansible.builtin.debug:
    msg: |
      Cleanup Summary:
      - Namespace: {{ namespace.result.metadata.labels['kubernetes.io/metadata.name'] }}
      - Temporary Directory: {{ teardown_test_temp_dir_path }}
