# roles/install_skupper/tasks/main.yml
---
- name: Cleaning skupper temprary directory
  ansible.builtin.file:
    dest: /tmp/skupper
    state: absent
    force: true

- name: Clone Skupper repository
  ansible.builtin.git:
    repo: "{{ install_skupper_skupper_repository }}"
    dest: /tmp/skupper
    version: "{{ install_skupper_skupper_branch }}"
    update: true

- name: Find CRDs in the directory
  ansible.builtin.find:
    paths: /tmp/skupper/api/types/crds/
    patterns: "*.yaml"
  register: crd_files

- name: Debug CRDs found
  ansible.builtin.debug:
    var: crd_files.files

- name: Install Skupper by applying CRDs
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item.path }}"
  loop: "{{ crd_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  failed_when: false

- name: Install the Skupper Controller
  kubernetes.core.k8s:
    state: present
    src: "{{ install_skupper_skupper_controller_manifest }}"
  register: skupper_controller_results
  failed_when: false

- name: Deleting Cloned Skupper repository directory
  ansible.builtin.file:
    dest: /tmp/skupper
    state: absent
  changed_when: false
