# roles/install_skupper/tasks/main.yml
---
- name: Create a folder name for git under skupper_install_output_path
  ansible.builtin.set_fact:
    skupper_folder: "{{ install_skupper_install_output_path }}/{{ inventory_hostname }}-skupper"

- name: Clone Skupper repository
  ansible.builtin.git:
    repo: "{{ install_skupper_skupper_repository }}"
    dest: "{{ skupper_folder }}"
    version: "{{ install_skupper_skupper_branch }}"
    update: true

- name: Install Skupper using Helm
  kubernetes.core.helm:
    chart_ref: "{{ skupper_folder }}/charts/skupper-setup"
    name: "{{ install_skupper_skupper_release_name }}"
    namespace: "{{ skupper_namespace | default('default') }}"
    values:
      scope: "cluster"

- name: Clean up Skupper repository directory
  ansible.builtin.file:
    path: "{{ skupper_folder }}"
    state: absent
    force: true
  changed_when: false
